<?php

namespace AppBundle\Repository\AddressBook;

use Doctrine\ORM\Mapping;
use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{

    public function createAlphabeticalQueryBuilder($country)
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.country = :country')
            ->setParameter('country', $country)
            ->orderBy('c.name', 'ASC');
    }

    public function createQueryBuilderAll()
    {
        return $this->createQueryBuilder('c')
            ->orderBy('c.name', 'ASC');
    }

}
